
package com.epam.lab.web.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-08-25T20:10:57.007+03:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "LibraryFault", targetNamespace = "http://soap.web.lab.epam.com/")
public class ServiceException extends Exception {
    
    private com.epam.lab.web.soap.LibraryFault libraryFault;

    public ServiceException() {
        super();
    }
    
    public ServiceException(String message) {
        super(message);
    }

    public ServiceException(LibraryFault faultInfo) {
        libraryFault = faultInfo;
    }
    
    public ServiceException(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException(String message, com.epam.lab.web.soap.LibraryFault libraryFault) {
        super(message);
        this.libraryFault = libraryFault;
    }

    public ServiceException(String message, com.epam.lab.web.soap.LibraryFault libraryFault, Throwable cause) {
        super(message, cause);
        this.libraryFault = libraryFault;
    }

    public com.epam.lab.web.soap.LibraryFault getFaultInfo() {
        return this.libraryFault;
    }
}
